baseURL: 'http://lynshi.github.io/'
title: "Nibbles and Bytes"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

# Sets up search...?
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  categories:
    - HTML
    - RSS
  tags:
    - HTML
    - RSS
  

outputFormats:
  outputFormats.RSS:
    mediaType: "application/rss+xml"
    baseName: "feed"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Nibbles and Bytes"
  description: "Lyndon Shi's blog :)"
  keywords: [Blog, Lyndon Shi]
  author: "Lyndon Shi"
  images: [] # "<link or path of image for opengraph, twitter-cards>"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "reddit"] # To customize which share buttons to be enabled on page
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon/favicon.png"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/favicon.png"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there, I'm Lyndon!"
    Content: |
      Welcome to my little corner of the Internet :)

      --

      Every once in a while I'll be inspired to write about something I learned and this is where
      that content goes. Hopefully someone out there will learn something new or find a solution to
      their issue here!

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/lynshi/"
    - name: github
      url: "https://github.com/lynshi"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/lynshi/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # For LaTeX
  math: true

menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Categories
      url: categories/
      weight: 15
    - name: Tags
      url: tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

taxonomies:
  category: categories
  tag: tags
  series: series